/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    contacts: Contact;
    broadcasts: Broadcast;
    emails: Email;
    pages: Page;
    emailUnsubscribeTokens: EmailUnsubscribeToken;
    formSubmissions: FormSubmission;
    forms: Form;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    contacts: {
      formSubmissions: 'formSubmissions';
    };
    broadcasts: {
      emails: 'emails';
    };
    forms: {
      formSubmissions: 'formSubmissions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    broadcasts: BroadcastsSelect<false> | BroadcastsSelect<true>;
    emails: EmailsSelect<false> | EmailsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    emailUnsubscribeTokens: EmailUnsubscribeTokensSelect<false> | EmailUnsubscribeTokensSelect<true>;
    formSubmissions: FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'send-broadcasts': TaskSendBroadcasts;
      'send-email': TaskSendEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  tags?: (number | Tag)[] | null;
  email: string;
  emailOptIn?: boolean | null;
  firstName?: string | null;
  lastName?: string | null;
  mobileNumber?: string | null;
  mobileOptIn?: boolean | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  country?:
    | (
        | 'AF'
        | 'AL'
        | 'DZ'
        | 'AS'
        | 'AD'
        | 'AO'
        | 'AI'
        | 'AQ'
        | 'AG'
        | 'AR'
        | 'AM'
        | 'AW'
        | 'AU'
        | 'AT'
        | 'AZ'
        | 'BS'
        | 'BH'
        | 'BD'
        | 'BB'
        | 'BY'
        | 'BE'
        | 'BZ'
        | 'BJ'
        | 'BM'
        | 'BT'
        | 'BO'
        | 'BA'
        | 'BW'
        | 'BV'
        | 'BR'
        | 'IO'
        | 'BN'
        | 'BG'
        | 'BF'
        | 'BI'
        | 'KH'
        | 'CM'
        | 'CA'
        | 'CV'
        | 'KY'
        | 'CF'
        | 'TD'
        | 'CL'
        | 'CN'
        | 'CX'
        | 'CC'
        | 'CO'
        | 'KM'
        | 'CG'
        | 'CD'
        | 'CK'
        | 'CR'
        | 'CI'
        | 'HR'
        | 'CU'
        | 'CY'
        | 'CZ'
        | 'DK'
        | 'DJ'
        | 'DM'
        | 'DO'
        | 'EC'
        | 'EG'
        | 'SV'
        | 'GQ'
        | 'ER'
        | 'EE'
        | 'ET'
        | 'FK'
        | 'FO'
        | 'FJ'
        | 'FI'
        | 'FR'
        | 'GF'
        | 'PF'
        | 'TF'
        | 'GA'
        | 'GM'
        | 'GE'
        | 'DE'
        | 'GH'
        | 'GI'
        | 'GR'
        | 'GL'
        | 'GD'
        | 'GP'
        | 'GU'
        | 'GT'
        | 'GN'
        | 'GW'
        | 'GY'
        | 'HT'
        | 'HM'
        | 'VA'
        | 'HN'
        | 'HK'
        | 'HU'
        | 'IS'
        | 'IN'
        | 'ID'
        | 'IR'
        | 'IQ'
        | 'IE'
        | 'IL'
        | 'IT'
        | 'JM'
        | 'JP'
        | 'JO'
        | 'KZ'
        | 'KE'
        | 'KI'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KG'
        | 'LA'
        | 'LV'
        | 'LB'
        | 'LS'
        | 'LR'
        | 'LY'
        | 'LI'
        | 'LT'
        | 'LU'
        | 'MO'
        | 'MG'
        | 'MW'
        | 'MY'
        | 'MV'
        | 'ML'
        | 'MT'
        | 'MH'
        | 'MQ'
        | 'MR'
        | 'MU'
        | 'YT'
        | 'MX'
        | 'FM'
        | 'MD'
        | 'MC'
        | 'MN'
        | 'MS'
        | 'MA'
        | 'MZ'
        | 'MM'
        | 'NA'
        | 'NR'
        | 'NP'
        | 'NL'
        | 'NC'
        | 'NZ'
        | 'NI'
        | 'NE'
        | 'NG'
        | 'NU'
        | 'NF'
        | 'MK'
        | 'MP'
        | 'NO'
        | 'OM'
        | 'PK'
        | 'PW'
        | 'PS'
        | 'PA'
        | 'PG'
        | 'PY'
        | 'PE'
        | 'PH'
        | 'PN'
        | 'PL'
        | 'PT'
        | 'PR'
        | 'QA'
        | 'RE'
        | 'RO'
        | 'RU'
        | 'RW'
        | 'SH'
        | 'KN'
        | 'LC'
        | 'PM'
        | 'VC'
        | 'WS'
        | 'SM'
        | 'ST'
        | 'SA'
        | 'SN'
        | 'SC'
        | 'SL'
        | 'SG'
        | 'SK'
        | 'SI'
        | 'SB'
        | 'SO'
        | 'ZA'
        | 'GS'
        | 'ES'
        | 'LK'
        | 'SD'
        | 'SR'
        | 'SJ'
        | 'SZ'
        | 'SE'
        | 'CH'
        | 'SY'
        | 'TW'
        | 'TJ'
        | 'TZ'
        | 'TH'
        | 'TL'
        | 'TG'
        | 'TK'
        | 'TO'
        | 'TT'
        | 'TN'
        | 'TR'
        | 'TM'
        | 'TC'
        | 'TV'
        | 'UG'
        | 'UA'
        | 'AE'
        | 'GB'
        | 'US'
        | 'UM'
        | 'UY'
        | 'UZ'
        | 'VU'
        | 'VE'
        | 'VN'
        | 'VG'
        | 'VI'
        | 'WF'
        | 'EH'
        | 'YE'
        | 'ZM'
        | 'ZW'
        | 'AX'
        | 'BQ'
        | 'CW'
        | 'GG'
        | 'IM'
        | 'JE'
        | 'ME'
        | 'BL'
        | 'MF'
        | 'RS'
        | 'SX'
        | 'SS'
        | 'XK'
      )
    | null;
  /**
   * Form submissions made by this contact
   */
  formSubmissions?: {
    docs?: (number | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  contact?: (number | null) | Contact;
  createdAt: string;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  status?: ('draft' | 'published') | null;
  name: string;
  slug: string;
  publishedAt?: string | null;
  headline?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legend?: string | null;
  /**
   * Configure the fields to be included in the contact form.
   */
  contactFields?:
    | (
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailOptIn';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'firstName';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lastName';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mobileNumber';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mobileOptIn';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'address';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'city';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'zip';
          }
        | {
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type?: ('reference' | 'custom') | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null);
  url?: string | null;
  /**
   * Tag all contacts submitted via this form with these tags.
   */
  tags?: (number | Tag)[] | null;
  autoresponse: {
    enabled?: boolean | null;
    fromName: string;
    /**
     * The from address is set in the email configuration.
     */
    fromAddress: string;
    replyTo?: string | null;
    subject?: string | null;
    previewText?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  formSubmissions?: {
    docs?: (number | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  status?: ('draft' | 'published') | null;
  name: string;
  slug: string;
  publishedAt?: string | null;
  blocks?:
    | (
        | ContentBlock
        | HeroBlock
        | HeaderBlock
        | GridBlock
        | ImageBlock
        | CTABlock
        | TeamBlock
        | StatsBlock
        | LogosBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  headline?: string | null;
  subheadline?: string | null;
  image?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        /**
         * Select the style for this button.
         */
        style: 'default' | 'secondary' | 'outline' | 'link' | 'ghost';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock".
 */
export interface HeaderBlock {
  headline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Header';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlock".
 */
export interface GridBlock {
  headline?: string | null;
  items?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  headline?: string | null;
  description?: string | null;
  buttons?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        /**
         * Select the style for this button.
         */
        style: 'default' | 'secondary' | 'outline' | 'link' | 'ghost';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CTA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  headline?: string | null;
  members?:
    | {
        name?: string | null;
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  headline?: string | null;
  description?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  headline?: string | null;
  logos?:
    | {
        name?: string | null;
        image: number | Media;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts".
 */
export interface Broadcast {
  id: number;
  status?: ('draft' | 'sending' | 'failed' | 'sent') | null;
  /**
   * This is for internal reference only.
   */
  name?: string | null;
  fromName: string;
  /**
   * The from address is set in the email configuration.
   */
  fromAddress: string;
  /**
   * Choose how to segment the recipients of this broadcast.
   */
  to?: ('all' | 'tags') | null;
  /**
   * Select one or more tags to send this broadcast to contacts with any of the selected tags who have opted in to receive emails.
   */
  tags?: (number | Tag)[] | null;
  replyTo?: string | null;
  subject: string;
  previewText?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  emails?: {
    docs?: (number | Email)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    contactsCount?: number | null;
    processedCount?: number | null;
    /**
     * Used for cursor-based pagination during batch processing
     */
    lastProcessedContactId?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emails".
 */
export interface Email {
  id: number;
  providerId?: string | null;
  status: 'queued' | 'failed' | 'sent' | 'delivered' | 'bounced' | 'unsubscribed' | 'complained';
  broadcast?: (number | null) | Broadcast;
  contact?: (number | null) | Contact;
  from: string;
  activity?:
    | {
        type: 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'unsubscribed' | 'complained';
        timestamp: string;
        id?: string | null;
      }[]
    | null;
  subject: string;
  to: string;
  html: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailUnsubscribeTokens".
 */
export interface EmailUnsubscribeToken {
  id: string;
  emailId?: (number | null) | Email;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'send-broadcasts' | 'send-email';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'send-broadcasts' | 'send-email') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'broadcasts';
        value: number | Broadcast;
      } | null)
    | ({
        relationTo: 'emails';
        value: number | Email;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'emailUnsubscribeTokens';
        value: string | EmailUnsubscribeToken;
      } | null)
    | ({
        relationTo: 'formSubmissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  tags?: T;
  email?: T;
  emailOptIn?: T;
  firstName?: T;
  lastName?: T;
  mobileNumber?: T;
  mobileOptIn?: T;
  address?: T;
  city?: T;
  state?: T;
  zip?: T;
  country?: T;
  formSubmissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts_select".
 */
export interface BroadcastsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  fromName?: T;
  fromAddress?: T;
  to?: T;
  tags?: T;
  replyTo?: T;
  subject?: T;
  previewText?: T;
  content?: T;
  emails?: T;
  meta?:
    | T
    | {
        contactsCount?: T;
        processedCount?: T;
        lastProcessedContactId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emails_select".
 */
export interface EmailsSelect<T extends boolean = true> {
  providerId?: T;
  status?: T;
  broadcast?: T;
  contact?: T;
  from?: T;
  activity?:
    | T
    | {
        type?: T;
        timestamp?: T;
        id?: T;
      };
  subject?: T;
  to?: T;
  html?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  slug?: T;
  publishedAt?: T;
  blocks?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        Hero?: T | HeroBlockSelect<T>;
        Header?: T | HeaderBlockSelect<T>;
        Grid?: T | GridBlockSelect<T>;
        Image?: T | ImageBlockSelect<T>;
        CTA?: T | CTABlockSelect<T>;
        Team?: T | TeamBlockSelect<T>;
        Stats?: T | StatsBlockSelect<T>;
        Logos?: T | LogosBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  image?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock_select".
 */
export interface HeaderBlockSelect<T extends boolean = true> {
  headline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlock_select".
 */
export interface GridBlockSelect<T extends boolean = true> {
  headline?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  headline?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  headline?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  headline?: T;
  description?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  headline?: T;
  logos?:
    | T
    | {
        name?: T;
        image?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailUnsubscribeTokens_select".
 */
export interface EmailUnsubscribeTokensSelect<T extends boolean = true> {
  id?: T;
  emailId?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  contact?: T;
  createdAt?: T;
  data?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  slug?: T;
  publishedAt?: T;
  headline?: T;
  content?: T;
  legend?: T;
  contactFields?:
    | T
    | {
        email?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        emailOptIn?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        firstName?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        lastName?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        mobileNumber?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        mobileOptIn?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        address?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        city?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        zip?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  type?: T;
  reference?: T;
  url?: T;
  tags?: T;
  autoresponse?:
    | T
    | {
        enabled?: T;
        fromName?: T;
        fromAddress?: T;
        replyTo?: T;
        subject?: T;
        previewText?: T;
        content?: T;
      };
  formSubmissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  navItems?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  navButtons?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        /**
         * Select the style for this button.
         */
        style: 'default' | 'secondary' | 'outline' | 'link' | 'ghost';
        id?: string | null;
      }[]
    | null;
  footerItems?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          page?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'forms';
                value: number | Form;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  navButtons?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        style?: T;
        id?: T;
      };
  footerItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-broadcasts".
 */
export interface TaskSendBroadcasts {
  input?: unknown;
  output: {
    success?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-email".
 */
export interface TaskSendEmail {
  input: {
    contactId: number;
    broadcastId: number;
  };
  output: {
    success?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}